export enum Category {
    DEFAULT = "DEFAULT",
    WOMEN_CLOTHES = "WOMEN_CLOTHES",
    MEN_CLOTHES = "MEN_CLOTHES",
    CHILDREN_CLOTHES = "CHILDREN_CLOTHES",
    COSMETICS = "COSMETICS",
    ACCESSORIES = "ACCESSORIES",
    HOUSEHOLD_SUPPLIES = "HOUSEHOLD_SUPPLIES",
    APPLIANCES = "APPLIANCES",
    ELECTRONICS = "ELECTRONICS",
    TOYS = "TOYS",
    BOOKS_MOVIES_MUSIC = "BOOKS_MOVIES_MUSIC",
    SHOES = "SHOES",
    SPORT_EQUIPMENT = "SPORT_EQUIPMENT",
    GARDEN_EQUIPMENT = "GARDEN_EQUIPMENT",
    OTHER = "OTHER"
}
